//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCBS.WpfApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCBS.WpfApp.Resources.Strings.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 language 的本地化字符串。
        /// </summary>
        public static string ApplicationSettingsPage_Language {
            get {
                return ResourceManager.GetString("ApplicationSettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Backdrop 的本地化字符串。
        /// </summary>
        public static string ApplicationSettingsPage_WindowBackdrop {
            get {
                return ResourceManager.GetString("ApplicationSettingsPage_WindowBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acrylic 的本地化字符串。
        /// </summary>
        public static string Backdrop_Acrylic {
            get {
                return ResourceManager.GetString("Backdrop_Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica 的本地化字符串。
        /// </summary>
        public static string Backdrop_Mica {
            get {
                return ResourceManager.GetString("Backdrop_Mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Backdrop_None {
            get {
                return ResourceManager.GetString("Backdrop_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Contrast 的本地化字符串。
        /// </summary>
        public static string Backdrop_Tabbed {
            get {
                return ResourceManager.GetString("Backdrop_Tabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_Client {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_CloseButton {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance Name 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_InstanceName {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_Path {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_PrimaryButton {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_PrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to select instance folder 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_SelectFolder {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select MC game folder 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_SelectFolder_Title {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_SelectFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_Server {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_ServerAddress {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Port 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_ServerPort {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Instance 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_Title {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Version 的本地化字符串。
        /// </summary>
        public static string CreateInstanceDialog_Version {
            get {
                return ResourceManager.GetString("CreateInstanceDialog_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Command {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Log {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSPT 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Mspt {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Mspt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Screen {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Instance 的本地化字符串。
        /// </summary>
        public static string InstanceManage_AddInstance {
            get {
                return ResourceManager.GetString("InstanceManage_AddInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh List 的本地化字符串。
        /// </summary>
        public static string InstanceManage_RefreshList {
            get {
                return ResourceManager.GetString("InstanceManage_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        public static string InstanceType_Client {
            get {
                return ResourceManager.GetString("InstanceType_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string InstanceType_Server {
            get {
                return ResourceManager.GetString("InstanceType_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Language_en_US {
            get {
                return ResourceManager.GetString("Language_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Language_zh_CN {
            get {
                return ResourceManager.GetString("Language_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Instance: 的本地化字符串。
        /// </summary>
        public static string LaunchPage_CurrentInstance {
            get {
                return ResourceManager.GetString("LaunchPage_CurrentInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Instance 的本地化字符串。
        /// </summary>
        public static string LaunchPage_LaunchInstance {
            get {
                return ResourceManager.GetString("LaunchPage_LaunchInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage FFmpeg 的本地化字符串。
        /// </summary>
        public static string LaunchPage_ManageFfmpeg {
            get {
                return ResourceManager.GetString("LaunchPage_ManageFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Instances 的本地化字符串。
        /// </summary>
        public static string LaunchPage_ManageInstances {
            get {
                return ResourceManager.GetString("LaunchPage_ManageInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Debugger {
            get {
                return ResourceManager.GetString("MainNavigation_Debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Home {
            get {
                return ResourceManager.GetString("MainNavigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Manager {
            get {
                return ResourceManager.GetString("MainNavigation_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulator 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Simulator {
            get {
                return ResourceManager.GetString("MainNavigation_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Application {
            get {
                return ResourceManager.GetString("ManagerNavigation_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Form {
            get {
                return ResourceManager.GetString("ManagerNavigation_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Process {
            get {
                return ResourceManager.GetString("ManagerNavigation_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resourcepack 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Resourcepack {
            get {
                return ResourceManager.GetString("ManagerNavigation_Resourcepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Screen {
            get {
                return ResourceManager.GetString("ManagerNavigation_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to leave this page 的本地化字符串。
        /// </summary>
        public static string MessageBox_Caption_ConfirmLeavePage {
            get {
                return ResourceManager.GetString("MessageBox_Caption_ConfirmLeavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance name &quot;{0}&quot; is invalid 的本地化字符串。
        /// </summary>
        public static string MessageBox_Caption_InvalidInstanceName {
            get {
                return ResourceManager.GetString("MessageBox_Caption_InvalidInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create instance 的本地化字符串。
        /// </summary>
        public static string MessageBox_Caption_UnableCreateInstance {
            get {
                return ResourceManager.GetString("MessageBox_Caption_UnableCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create instance &quot;{0}&quot;.
        ///{1} 的本地化字符串。
        /// </summary>
        public static string MessageBox_Error_CreateInstanceFailed {
            get {
                return ResourceManager.GetString("MessageBox_Error_CreateInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete instance &quot;{0}&quot;.
        ///{1} 的本地化字符串。
        /// </summary>
        public static string MessageBox_Error_DeleteInstanceFailed {
            get {
                return ResourceManager.GetString("MessageBox_Error_DeleteInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to rename instance: &quot;{0}&quot; -&gt; &quot;{1}&quot;
        ///{2} 的本地化字符串。
        /// </summary>
        public static string MessageBox_Error_RenameInstanceFailed {
            get {
                return ResourceManager.GetString("MessageBox_Error_RenameInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to access instance list, please try again later.
        ///{0} 的本地化字符串。
        /// </summary>
        public static string MessageBox_Error_UnableAccessInstanceList {
            get {
                return ResourceManager.GetString("MessageBox_Error_UnableAccessInstanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal error 的本地化字符串。
        /// </summary>
        public static string MessageBox_Fatal {
            get {
                return ResourceManager.GetString("MessageBox_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string MessageBox_Info {
            get {
                return ResourceManager.GetString("MessageBox_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn {
            get {
                return ResourceManager.GetString("MessageBox_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete instance &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn_ConfirmDeleteInstance {
            get {
                return ResourceManager.GetString("MessageBox_Warn_ConfirmDeleteInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance name &quot;{0}&quot; already exists, please use a different name. 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn_InstanceNameExists {
            get {
                return ResourceManager.GetString("MessageBox_Warn_InstanceNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following properties are not set correctly:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn_InvalidProperties {
            get {
                return ResourceManager.GetString("MessageBox_Warn_InvalidProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance &quot;{0}&quot; cannot be deleted. 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn_UnableDeleteInstance {
            get {
                return ResourceManager.GetString("MessageBox_Warn_UnableDeleteInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance &quot;{0}&quot; cannot be renamed to &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        public static string MessageBox_Warn_UnableRenameInstance {
            get {
                return ResourceManager.GetString("MessageBox_Warn_UnableRenameInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings related to graphical interface applications 的本地化字符串。
        /// </summary>
        public static string Settings_ApplicationSettings_Description {
            get {
                return ResourceManager.GetString("Settings_ApplicationSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings 的本地化字符串。
        /// </summary>
        public static string Settings_ApplicationSettings_Header {
            get {
                return ResourceManager.GetString("Settings_ApplicationSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Environment Configuration 的本地化字符串。
        /// </summary>
        public static string Settings_MinecraftSettings_Description {
            get {
                return ResourceManager.GetString("Settings_MinecraftSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Settings 的本地化字符串。
        /// </summary>
        public static string Settings_MinecraftSettings_Header {
            get {
                return ResourceManager.GetString("Settings_MinecraftSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In game screen parameter configuration 的本地化字符串。
        /// </summary>
        public static string Settings_ScreenSettings_Description {
            get {
                return ResourceManager.GetString("Settings_ScreenSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Settings 的本地化字符串。
        /// </summary>
        public static string Settings_ScreenSettings_Header {
            get {
                return ResourceManager.GetString("Settings_ScreenSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCBS system related settings 的本地化字符串。
        /// </summary>
        public static string Settings_SystemSettings_Description {
            get {
                return ResourceManager.GetString("Settings_SystemSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings 的本地化字符串。
        /// </summary>
        public static string Settings_SystemSettings_Header {
            get {
                return ResourceManager.GetString("Settings_SystemSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Manager 的本地化字符串。
        /// </summary>
        public static string Title_ApplicationManagerPage {
            get {
                return ResourceManager.GetString("Title_ApplicationManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings 的本地化字符串。
        /// </summary>
        public static string Title_ApplicationSettingsPage {
            get {
                return ResourceManager.GetString("Title_ApplicationSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Analyzer 的本地化字符串。
        /// </summary>
        public static string Title_CommandAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_CommandAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONSOLE Configuration 的本地化字符串。
        /// </summary>
        public static string Title_ConsoleModeConfigPage {
            get {
                return ResourceManager.GetString("Title_ConsoleModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger 的本地化字符串。
        /// </summary>
        public static string Title_DebuggerPage {
            get {
                return ResourceManager.GetString("Title_DebuggerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Manager 的本地化字符串。
        /// </summary>
        public static string Title_FormManagerPage {
            get {
                return ResourceManager.GetString("Title_FormManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Title_HomePage {
            get {
                return ResourceManager.GetString("Title_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance Manager 的本地化字符串。
        /// </summary>
        public static string Title_InstanceManagePage {
            get {
                return ResourceManager.GetString("Title_InstanceManagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        public static string Title_LaunchPage {
            get {
                return ResourceManager.GetString("Title_LaunchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Manager 的本地化字符串。
        /// </summary>
        public static string Title_LogManagerPage {
            get {
                return ResourceManager.GetString("Title_LogManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Block Screen 的本地化字符串。
        /// </summary>
        public static string Title_MainWindow {
            get {
                return ResourceManager.GetString("Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        public static string Title_ManagerPage {
            get {
                return ResourceManager.GetString("Title_ManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCAPI Config 的本地化字符串。
        /// </summary>
        public static string Title_McapiModeConfigPage {
            get {
                return ResourceManager.GetString("Title_McapiModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Settings 的本地化字符串。
        /// </summary>
        public static string Title_MinecraftSettingsPage {
            get {
                return ResourceManager.GetString("Title_MinecraftSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSPT Analyzer 的本地化字符串。
        /// </summary>
        public static string Title_MsptAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_MsptAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Manager 的本地化字符串。
        /// </summary>
        public static string Title_ProcessManagerPage {
            get {
                return ResourceManager.GetString("Title_ProcessManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RCON Config 的本地化字符串。
        /// </summary>
        public static string Title_RconModeConfigPage {
            get {
                return ResourceManager.GetString("Title_RconModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resourcepack Manager 的本地化字符串。
        /// </summary>
        public static string Title_ResourcepackManagerPage {
            get {
                return ResourceManager.GetString("Title_ResourcepackManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Analyzer 的本地化字符串。
        /// </summary>
        public static string Title_ScreenAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_ScreenAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Manager 的本地化字符串。
        /// </summary>
        public static string Title_ScreenManagerPage {
            get {
                return ResourceManager.GetString("Title_ScreenManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Settings 的本地化字符串。
        /// </summary>
        public static string Title_ScreenSettingsPage {
            get {
                return ResourceManager.GetString("Title_ScreenSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Title_SettingsPage {
            get {
                return ResourceManager.GetString("Title_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulator 的本地化字符串。
        /// </summary>
        public static string Title_SimulatorPage {
            get {
                return ResourceManager.GetString("Title_SimulatorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings 的本地化字符串。
        /// </summary>
        public static string Title_SystemSettingsPage {
            get {
                return ResourceManager.GetString("Title_SystemSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch To Dark 的本地化字符串。
        /// </summary>
        public static string ToggleButton_SwitchToDark {
            get {
                return ResourceManager.GetString("ToggleButton_SwitchToDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch To Light 的本地化字符串。
        /// </summary>
        public static string ToggleButton_SwitchToLight {
            get {
                return ResourceManager.GetString("ToggleButton_SwitchToLight", resourceCulture);
            }
        }
    }
}
