//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCBS.WpfApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCBS.WpfApp.Resources.Strings.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 language 的本地化字符串。
        /// </summary>
        public static string ApplicationSettingsPage_Language {
            get {
                return ResourceManager.GetString("ApplicationSettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Command {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Log {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSPT 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Mspt {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Mspt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        public static string DebuggerNavigation_Screen {
            get {
                return ResourceManager.GetString("DebuggerNavigation_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Language_en_US {
            get {
                return ResourceManager.GetString("Language_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Language_zh_CN {
            get {
                return ResourceManager.GetString("Language_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Debugger {
            get {
                return ResourceManager.GetString("MainNavigation_Debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Home {
            get {
                return ResourceManager.GetString("MainNavigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Manager {
            get {
                return ResourceManager.GetString("MainNavigation_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulator 的本地化字符串。
        /// </summary>
        public static string MainNavigation_Simulator {
            get {
                return ResourceManager.GetString("MainNavigation_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Application {
            get {
                return ResourceManager.GetString("ManagerNavigation_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Form {
            get {
                return ResourceManager.GetString("ManagerNavigation_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Process {
            get {
                return ResourceManager.GetString("ManagerNavigation_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resourcepack 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Resourcepack {
            get {
                return ResourceManager.GetString("ManagerNavigation_Resourcepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        public static string ManagerNavigation_Screen {
            get {
                return ResourceManager.GetString("ManagerNavigation_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings related to graphical interface applications 的本地化字符串。
        /// </summary>
        public static string Settings_ApplicationSettings_Description {
            get {
                return ResourceManager.GetString("Settings_ApplicationSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings 的本地化字符串。
        /// </summary>
        public static string Settings_ApplicationSettings_Header {
            get {
                return ResourceManager.GetString("Settings_ApplicationSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Environment Configuration 的本地化字符串。
        /// </summary>
        public static string Settings_MinecraftSettings_Description {
            get {
                return ResourceManager.GetString("Settings_MinecraftSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Settings 的本地化字符串。
        /// </summary>
        public static string Settings_MinecraftSettings_Header {
            get {
                return ResourceManager.GetString("Settings_MinecraftSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In game screen parameter configuration 的本地化字符串。
        /// </summary>
        public static string Settings_ScreenSettings_Description {
            get {
                return ResourceManager.GetString("Settings_ScreenSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Settings 的本地化字符串。
        /// </summary>
        public static string Settings_ScreenSettings_Header {
            get {
                return ResourceManager.GetString("Settings_ScreenSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCBS system related settings 的本地化字符串。
        /// </summary>
        public static string Settings_SystemSettings_Description {
            get {
                return ResourceManager.GetString("Settings_SystemSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings 的本地化字符串。
        /// </summary>
        public static string Settings_SystemSettings_Header {
            get {
                return ResourceManager.GetString("Settings_SystemSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_ApplicationManagerPage {
            get {
                return ResourceManager.GetString("Title_ApplicationManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings Page 的本地化字符串。
        /// </summary>
        public static string Title_ApplicationSettingsPage {
            get {
                return ResourceManager.GetString("Title_ApplicationSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Analyzer Page 的本地化字符串。
        /// </summary>
        public static string Title_CommandAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_CommandAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONSOLE Configuration 的本地化字符串。
        /// </summary>
        public static string Title_ConsoleModeConfigPage {
            get {
                return ResourceManager.GetString("Title_ConsoleModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger Page 的本地化字符串。
        /// </summary>
        public static string Title_DebuggerPage {
            get {
                return ResourceManager.GetString("Title_DebuggerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_FormManagerPage {
            get {
                return ResourceManager.GetString("Title_FormManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        public static string Title_HomePage {
            get {
                return ResourceManager.GetString("Title_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_LogManagerPage {
            get {
                return ResourceManager.GetString("Title_LogManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Block Screen 的本地化字符串。
        /// </summary>
        public static string Title_MainWindow {
            get {
                return ResourceManager.GetString("Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_ManagerPage {
            get {
                return ResourceManager.GetString("Title_ManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCAPI Config Page 的本地化字符串。
        /// </summary>
        public static string Title_McapiModeConfigPage {
            get {
                return ResourceManager.GetString("Title_McapiModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Settings Page 的本地化字符串。
        /// </summary>
        public static string Title_MinecraftSettingsPage {
            get {
                return ResourceManager.GetString("Title_MinecraftSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSPT Analyzer Page 的本地化字符串。
        /// </summary>
        public static string Title_MsptAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_MsptAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_ProcessManagerPage {
            get {
                return ResourceManager.GetString("Title_ProcessManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RCON Config Page 的本地化字符串。
        /// </summary>
        public static string Title_RconModeConfigPage {
            get {
                return ResourceManager.GetString("Title_RconModeConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resourcepack Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_ResourcepackManagerPage {
            get {
                return ResourceManager.GetString("Title_ResourcepackManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Analyzer Page 的本地化字符串。
        /// </summary>
        public static string Title_ScreenAnalyzerPage {
            get {
                return ResourceManager.GetString("Title_ScreenAnalyzerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Manager Page 的本地化字符串。
        /// </summary>
        public static string Title_ScreenManagerPage {
            get {
                return ResourceManager.GetString("Title_ScreenManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Settings Page 的本地化字符串。
        /// </summary>
        public static string Title_ScreenSettingsPage {
            get {
                return ResourceManager.GetString("Title_ScreenSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings Page 的本地化字符串。
        /// </summary>
        public static string Title_SettingsPage {
            get {
                return ResourceManager.GetString("Title_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulator Page 的本地化字符串。
        /// </summary>
        public static string Title_SimulatorPage {
            get {
                return ResourceManager.GetString("Title_SimulatorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings Page 的本地化字符串。
        /// </summary>
        public static string Title_SystemSettingsPage {
            get {
                return ResourceManager.GetString("Title_SystemSettingsPage", resourceCulture);
            }
        }
    }
}
