#Minecraft游戏版本
GameVersion = "1.20.1"

#Minecraft实例类型
#可接受的参数: CLIENT, SERVER
#CLIENT: 客户端
#SERVER: 服务端
InstanceType = "CLIENT"

#与Minecraft实例的通信模式
#可接受的参数: RCON, CONSOLE, HYBRID, MCAPI
#RCON: 连接到已启动的Minecraft服务端，使用RCON进行通信，仅支持服务端
#CONSOLE: 启动一个新的Minecraft服务端进程，使用控制台输入输出流进行通信，仅支持服务端
#HYBRID: 启动一个新的Minecraft服务端进程，发送单条命令时使用RCON，发送批量命令时使用控制台输入输出流，仅支持服务端
#MCAPI: 连接到已启动的Minecraft服务端，使用MCAPI模组进行通信
CommunicationMode = "MCAPI"

#提供Minecraft原版资源下载服务的API
#可接受的参数: MOJANG, BMCLAPI
#MOJANG: 从MOJANG官方API下载
#BMCLAPI: 从BMCLAPI下载
DownloadApi = "BMCLAPI"

#Minecraft主目录所在路径
#"."为程序工作目录
#".."为程序工作目录的上一层目录
MinecraftPath = "."

#服务器IP地址，同时也作为RCON和MCAPI的IP地址
#不能为空
ServerAddress = "127.0.0.1"

#启动服务端进程所使用的Java路径
#当配置项 CommunicationMode 的值为 CONSOLE 或 HYBRID 时，当前配置项的值不能为空
JavaPath = ""

#启动服务端进程所使用的启动参数
#当配置项 CommunicationMode 的值为 CONSOLE 或 HYBRID 时，当前配置项的值不能为空
LaunchArguments = ""

#MCAPI端口
#范围: 0~65535
McapiPort = 25585

#MCAPI登录密码
#当配置项 CommunicationMode 的值为 MCAPI 时，当前配置项的值不能为空
McapiPassword = "123456"

#语言标识
#支持的文件类型: 语言文件.json
#文件目录: MCBS\Minecraft\Vanilla\{版本}\Languages\
#服务端语言默认为en_us，客户端根据选择的语言设置
#不能为空
Language = "zh_cn"

#资源包列表
#支持的文件类型: 客户端核心.jar, 服务端核心.jar, 模组文件.jar, 资源包.zip
#文件目录: MCBS\Minecraft\ResourcePacks\
#加载顺序: 从前往后加载
ResourcePackList = []

#屏幕方块黑名单列表
BlockTextureBlacklist = [
"minecraft:glowstone",                  #萤石
"minecraft:jack_o_lantern",             #南瓜灯
"minecraft:sea_lantern",                #海晶灯
"minecraft:ochre_froglight",            #赭黄蛙明灯
"minecraft:verdant_froglight",          #青翠蛙明灯
"minecraft:pearlescent_froglight",      #珠光蛙明灯
"minecraft:shroomlight",                #菌光体
"minecraft:redstone_lamp[lit=true]",    #红石灯（点亮）
"minecraft:crying_obsidian",            #哭泣的黑曜石
"minecraft:magma_block",                #岩浆块
"minecraft:sculk_catalyst",             #幽匿催发体
"minecraft:beacon",                     #信标
"minecraft:respawn_anchor[charges=1]",  #重生锚（充能等级1）
"minecraft:respawn_anchor[charges=2]",  #重生锚（充能等级2）
"minecraft:respawn_anchor[charges=3]",  #重生锚（充能等级2）
"minecraft:respawn_anchor[charges=4]",  #重生锚（充能等级4）
"minecraft:furnace[lit=true]",          #熔炉（燃烧中）
"minecraft:smoker[lit=true]",           #烟熏炉（燃烧中）
"minecraft:blast_furnace[lit=true]",    #高炉（燃烧中）
"minecraft:grass_block",                #草方块
"minecraft:podzol",                     #灰化土
"minecraft:mycelium",                   #菌丝体
"minecraft:crimson_nylium",             #绯红菌岩
"minecraft:warped_nylium",              #诡异菌岩
"minecraft:tnt",                        #TNT
"minecraft:snow",                       #雪片
"minecraft:budding_amethyst",           #紫水晶母岩
"minecraft:tube_coral_block",           #管珊瑚块
"minecraft:brain_coral_block",          #脑纹珊瑚块
"minecraft:bubble_coral_block",         #气泡珊瑚块
"minecraft:fire_coral_block",           #火珊瑚块
"minecraft:horn_coral_block",           #鹿角珊瑚块
]