#屏幕数量限制
#范围: 0~64
MaxCount = 8

#屏幕最小长度限制
#范围: 1~512
MinLength = 32

#屏幕最大长度限制
#范围: 1~512
MaxLength = 256

#屏幕最小像素数量限制
#范围: 1~262144
MinPixels = 1024

#屏幕最大像素数量限制
#范围: 1~262144
MaxPixels = 65536

#屏幕最小Y轴限制
#1.17及以下设置为0
#1.18及以上设置为-64
MinY = -64

#屏幕最大Y轴限制
#1.17及以下设置为255
#1.18及以上设置为319
MaxY = 319

#屏幕构造器超时时间
#设置为-1时将无限等待，不会超时
#单位: GameTick
#范围: -1~214748367
ScreenBuildTimeout = 200

#屏幕闲置超时时间
#设置为-1时将无限等待，不会超时
#单位: GameTick
#范围: -1~214748367
ScreenIdleTimeout = -1

#用于触发右键点击操作的计分板名称
#不能为空
RightClickObjective = "snowball_mouse"

#用于触发右键点击操作的计分板准则
#不能为空
RightClickCriterion = "minecraft.used:minecraft.snowball"

#用于触发右键点击操作的物品ID
#不能为空
RightClickItemID = "minecraft:snowball"

#用于编辑屏幕文本的物品ID
#一般情况下不支持修改，除非自定义物品的NBT标签结构与书与笔一致
TextEditorItemID = "minecraft:writable_book"

#用于载入屏幕构建器的物品名称
#将雪球命名重命名为该名称后，手持雪球载入屏幕创建程序
ScreenBuilderItemName = "创建屏幕"

#允许控制屏幕的玩家白名单列表
#填写玩家名称
#为空时，所有人都可以控制屏幕
ScreenOperatorList = []

#允许创建屏幕的玩家白名单列表
#填写玩家名称
#为空时，所有人都可以创建屏幕
ScreenBuildOperatorList = []

#常驻屏幕列表
#示例模板：
#[[ResidentScreenList]]
#StartPosition = [0, 83, 0] #屏幕的起始位置，既屏幕左上角在世界中的位置
#Width = 256                #屏幕的宽度，范围: 1~512
#Height = 144               #屏幕的高度，范围: 1~512
#XFacing = -1               #屏幕的X轴在世界轴中的延伸方向   1=X轴正方向  2=Y轴正方向  3=Z轴正方向
#YFacing = -2               #屏幕的Y轴在世界轴中的延伸方向  -1=X轴负方向 -2=Y轴负方向 -3=Z轴负方向
ResidentScreenList = []