#崩溃时是否自动重启
CrashAutoRestart = true

#启动时是否构建Minecraft方块颜色映射表缓存
BuildColorMappingCaches = false

#是否加载“MCBS\DllAppComponents\”目录下的DLL应用程序
#支持的文件类型: 程序集.dll
LoadDllAppComponents = false

#系统应用程序加载列表
#值为引用的程序集名称
SystemAppComponents = [
    "MCBS.SystemApplications.Services",
    "MCBS.SystemApplications.Desktop",
    "MCBS.SystemApplications.Console",
    "MCBS.SystemApplications.Settings",
    "MCBS.SystemApplications.TaskManager",
    "MCBS.SystemApplications.FileExplorer",
    "MCBS.SystemApplications.ScreenManager",
    "MCBS.SystemApplications.ScreenAdjuster",
    "MCBS.SystemApplications.VideoPlayer",
    "MCBS.SystemApplications.Album",
    "MCBS.SystemApplications.Drawing",
    "MCBS.SystemApplications.Notepad",
    "MCBS.SystemApplications.QRCodeGenerator",
    "MCBS.SystemApplications.DataScreen"
]

#系统服务AppID
ServicesAppID = "System.Services"

#启动项AppID列表
StartupChecklist = [
    "System.Desktop"
]